routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProjectUserController;
use App\Http\Controllers\ProjectDataController;
use App\Http\Controllers\ProjectMetaController;
use App\Http\Controllers\ProjectLoadFileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/home/{uid}', [HomeController::class, 'setActiveProject']);
Route::get('/sessions', [HomeController::class, 'SessionsDate']);

Route::prefix('/')
    ->middleware('auth')
    ->group(function () {
        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);

        Route::resource('users', UserController::class);
        Route::resource('project-users', ProjectUserController::class);
        Route::resource('project-load-files', ProjectLoadFileController::class);
        Route::get('all-project-data', [
            ProjectDataController::class,
            'index',
        ])->name('all-project-data.index');
        Route::post('all-project-data', [
            ProjectDataController::class,
            'store',
        ])->name('all-project-data.store');
        Route::get('all-project-data/create', [
            ProjectDataController::class,
            'create',
        ])->name('all-project-data.create');
        Route::get('all-project-data/{projectData}', [
            ProjectDataController::class,
            'show',
        ])->name('all-project-data.show');
        Route::get('all-project-data/{projectData}/edit', [
            ProjectDataController::class,
            'edit',
        ])->name('all-project-data.edit');
        Route::put('all-project-data/{projectData}', [
            ProjectDataController::class,
            'update',
        ])->name('all-project-data.update');
        Route::delete('all-project-data/{projectData}', [
            ProjectDataController::class,
            'destroy',
        ])->name('all-project-data.destroy');

        Route::resource('projects', ProjectController::class);
        Route::resource('project-metas', ProjectMetaController::class);
    });

app/Models/ProjectLoadFile.php
<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class ProjectLoadFile extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = ['project_id', 'filename'];

    protected $searchableFields = ['*'];

    protected $table = 'project_load_files';

    public function project()
    {
        return $this->belongsTo(Project::class);
    }
}

app/Http/Controllers/Api/ProjectLoadFileController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Models\ProjectLoadFile;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use App\Http\Resources\ProjectLoadFileResource;
use App\Http\Resources\ProjectLoadFileCollection;
use App\Http\Requests\ProjectLoadFileStoreRequest;
use App\Http\Requests\ProjectLoadFileUpdateRequest;

class ProjectLoadFileController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', ProjectLoadFile::class);

        $search = $request->get('search', '');

        $projectLoadFiles = ProjectLoadFile::search($search)
            ->latest()
            ->paginate();

        return new ProjectLoadFileCollection($projectLoadFiles);
    }

    /**
     * @param \App\Http\Requests\ProjectLoadFileStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectLoadFileStoreRequest $request)
    {
        $this->authorize('create', ProjectLoadFile::class);

        $validated = $request->validated();
        if ($request->hasFile('filename')) {
            $validated['filename'] = $request
                ->file('filename')
                ->store('public');
        }

        $projectLoadFile = ProjectLoadFile::create($validated);

        return new ProjectLoadFileResource($projectLoadFile);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectLoadFile $projectLoadFile
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, ProjectLoadFile $projectLoadFile)
    {
        $this->authorize('view', $projectLoadFile);

        return new ProjectLoadFileResource($projectLoadFile);
    }

    /**
     * @param \App\Http\Requests\ProjectLoadFileUpdateRequest $request
     * @param \App\Models\ProjectLoadFile $projectLoadFile
     * @return \Illuminate\Http\Response
     */
    public function update(
        ProjectLoadFileUpdateRequest $request,
        ProjectLoadFile $projectLoadFile
    ) {
        $this->authorize('update', $projectLoadFile);

        $validated = $request->validated();

        if ($request->hasFile('filename')) {
            if ($projectLoadFile->filename) {
                Storage::delete($projectLoadFile->filename);
            }

            $validated['filename'] = $request
                ->file('filename')
                ->store('public');
        }

        $projectLoadFile->update($validated);

        return new ProjectLoadFileResource($projectLoadFile);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectLoadFile $projectLoadFile
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, ProjectLoadFile $projectLoadFile)
    {
        $this->authorize('delete', $projectLoadFile);

        if ($projectLoadFile->filename) {
            Storage::delete($projectLoadFile->filename);
        }

        $projectLoadFile->delete();

        return response()->noContent();
    }
}

app/Http/Controllers/ProjectLoadFileController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;
use App\Models\ProjectLoadFile;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\ProjectLoadFileStoreRequest;
use App\Http\Requests\ProjectLoadFileUpdateRequest;

class ProjectLoadFileController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', ProjectLoadFile::class);

        $search = $request->get('search', '');

        $projectLoadFiles = ProjectLoadFile::search($search)
            ->latest()
            ->paginate(5)
            ->withQueryString();

        return view(
            'app.project_load_files.index',
            compact('projectLoadFiles', 'search')
        );
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $this->authorize('create', ProjectLoadFile::class);

        $projects = Project::pluck('name', 'id');

        return view('app.project_load_files.create', compact('projects'));
    }

    /**
     * @param \App\Http\Requests\ProjectLoadFileStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectLoadFileStoreRequest $request)
    {
        $this->authorize('create', ProjectLoadFile::class);

        $validated = $request->validated();
        if ($request->hasFile('filename')) {
            $validated['filename'] = $request
                ->file('filename')
                ->store('public');
        }

        $projectLoadFile = ProjectLoadFile::create($validated);

        return redirect()
            ->route('project-load-files.edit', $projectLoadFile)
            ->withSuccess(__('crud.common.created'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectLoadFile $projectLoadFile
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, ProjectLoadFile $projectLoadFile)
    {
        $this->authorize('view', $projectLoadFile);

        return view('app.project_load_files.show', compact('projectLoadFile'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectLoadFile $projectLoadFile
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, ProjectLoadFile $projectLoadFile)
    {
        $this->authorize('update', $projectLoadFile);

        $projects = Project::pluck('name', 'id');

        return view(
            'app.project_load_files.edit',
            compact('projectLoadFile', 'projects')
        );
    }

    /**
     * @param \App\Http\Requests\ProjectLoadFileUpdateRequest $request
     * @param \App\Models\ProjectLoadFile $projectLoadFile
     * @return \Illuminate\Http\Response
     */
    public function update(
        ProjectLoadFileUpdateRequest $request,
        ProjectLoadFile $projectLoadFile
    ) {
        $this->authorize('update', $projectLoadFile);

        $validated = $request->validated();
        if ($request->hasFile('filename')) {
            if ($projectLoadFile->filename) {
                Storage::delete($projectLoadFile->filename);
            }

            $validated['filename'] = $request
                ->file('filename')
                ->store('public');
        }

        $projectLoadFile->update($validated);

        return redirect()
            ->route('project-load-files.edit', $projectLoadFile)
            ->withSuccess(__('crud.common.saved'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectLoadFile $projectLoadFile
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, ProjectLoadFile $projectLoadFile)
    {
        $this->authorize('delete', $projectLoadFile);

        if ($projectLoadFile->filename) {
            Storage::delete($projectLoadFile->filename);
        }

        $projectLoadFile->delete();

        return redirect()
            ->route('project-load-files.index')
            ->withSuccess(__('crud.common.removed'));
    }
}

resources/views/app/project_load_files/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('project-load-files.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.project_load_files.create_title')
            </h4>

            <x-form
                method="POST"
                action="{{ route('project-load-files.store') }}"
                has-files
                class="mt-4"
            >
                @include('app.project_load_files.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('project-load-files.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.create')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

resources/views/app/project_load_files/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('project-load-files.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.project_load_files.edit_title')
            </h4>

            <x-form
                method="PUT"
                action="{{ route('project-load-files.update', $projectLoadFile) }}"
                has-files
                class="mt-4"
            >
                @include('app.project_load_files.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('project-load-files.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <a
                        href="{{ route('project-load-files.create') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-add text-primary"></i>
                        @lang('crud.common.create')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.update')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

resources/views/app/project_load_files/form-inputs.blade.php
@php $editing = isset($projectLoadFile) @endphp

<div class="row">
    <x-inputs.group class="col-sm-12">
        <x-inputs.select name="project_id" label="Project" required>
            @php $selected = old('project_id', ($editing ? $projectLoadFile->project_id : '')) @endphp
            <option disabled {{ empty($selected) ? 'selected' : '' }}>Please select the Project</option>
            @foreach($projects as $value => $label)
            <option value="{{ $value }}" {{ $selected == $value ? 'selected' : '' }} >{{ $label }}</option>
            @endforeach
        </x-inputs.select>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12">
        <x-inputs.partials.label
            name="filename"
            label="Filename"
        ></x-inputs.partials.label
        ><br />

        <input
            type="file"
            name="filename"
            id="filename"
            class="form-control-file"
        />

        @if($editing && $projectLoadFile->filename)
        <div class="mt-2">
            <a
                href="{{ \Storage::url($projectLoadFile->filename) }}"
                target="_blank"
                ><i class="icon ion-md-download"></i>&nbsp;Download</a
            >
        </div>
        @endif @error('filename') @include('components.inputs.partials.error')
        @enderror
    </x-inputs.group>
</div>

resources/views/app/project_load_files/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="searchbar mt-0 mb-4">
            <div class="row">
                <div class="col-md-6">
                    <form>
                        <div class="input-group">
                            <input
                                id="indexSearch"
                                type="text"
                                name="search"
                                placeholder="{{ __('crud.common.search') }}"
                                value="{{ $search ?? '' }}"
                                class="form-control"
                                autocomplete="off"
                            />
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">
                                    <i class="icon ion-md-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-6 text-right">
                    @can('create', App\Models\ProjectLoadFile::class)
                        <a
                            href="{{ route('project-load-files.create') }}"
                            class="btn btn-primary"
                        >
                            <i class="icon ion-md-add"></i> @lang('crud.common.create')
                        </a>
                    @endcan
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <div style="display: flex; justify-content: space-between;">
                    <h4 class="card-title">
                        @lang('crud.project_load_files.index_title')
                    </h4>
                </div>

                <div class="table-responsive">
                    <table class="table table-borderless table-hover">
                        <thead>
                        <tr>
                            <th class="text-left">
                                @lang('crud.project_load_files.inputs.project_id')
                            </th>
                            <th class="text-left">
                                @lang('crud.project_load_files.inputs.filename')
                            </th>
                            <th class="text-center">
                                @lang('crud.common.actions')
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($projectLoadFiles as $projectLoadFile)
                            <tr>
                                <td>
                                    {{ optional($projectLoadFile->project)->name ??
                                    '-' }}
                                </td>
                                <td>
                                    @if($projectLoadFile->filename)
                                        <a href="{{ \Storage::url($projectLoadFile->filename) }}"
                                           target="blank">
                                            <i class="icon ion-md-download"></i>&nbsp;
                                            Download
                                        </a>
                                    <br>
                                        <span>{{ str_replace('public/files/', '', $projectLoadFile->filename) }}</span>
                                    @else - @endif
                                </td>
                                <td class="text-center" style="width: 134px;">
                                    <div
                                        role="group"
                                        aria-label="Row Actions"
                                        class="btn-group"
                                    >
                                        @can('update', $projectLoadFile)
                                            <a
                                                href="{{ route('project-load-files.edit', $projectLoadFile) }}"
                                            >
                                                <button
                                                    type="button"
                                                    class="btn btn-light"
                                                >
                                                    <i class="icon ion-md-create"></i>
                                                </button>
                                            </a>
                                        @endcan @can('view', $projectLoadFile)
                                            <a
                                                href="{{ route('project-load-files.show', $projectLoadFile) }}"
                                            >
                                                <button
                                                    type="button"
                                                    class="btn btn-light"
                                                >
                                                    <i class="icon ion-md-eye"></i>
                                                </button>
                                            </a>
                                        @endcan @can('delete', $projectLoadFile)
                                            <form
                                                action="{{ route('project-load-files.destroy', $projectLoadFile) }}"
                                                method="POST"
                                                onsubmit="return confirm('{{ __('crud.common.are_you_sure') }}')"
                                            >
                                                @csrf @method('DELETE')
                                                <button
                                                    type="submit"
                                                    class="btn btn-light text-danger"
                                                >
                                                    <i class="icon ion-md-trash"></i>
                                                </button>
                                            </form>
                                        @endcan
                                    </div>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="3">
                                    @lang('crud.common.no_items_found')
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="3">
                                {!! $projectLoadFiles->render() !!}
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/app/project_load_files/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('project-load-files.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.project_load_files.show_title')
            </h4>

            <div class="mt-4">
                <div class="mb-4">
                    <h5>@lang('crud.project_load_files.inputs.project_id')</h5>
                    <span
                        >{{ optional($projectLoadFile->project)->name ?? '-'
                        }}</span
                    >
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.project_load_files.inputs.filename')</h5>
                    @if($projectLoadFile->filename)
                    <a
                        href="{{ \Storage::url($projectLoadFile->filename) }}"
                        target="blank"
                        ><i class="icon ion-md-download"></i>&nbsp;Download</a
                    >
                    @else - @endif
                </div>
            </div>

            <div class="mt-4">
                <a
                    href="{{ route('project-load-files.index') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-return-left"></i>
                    @lang('crud.common.back')
                </a>

                @can('create', App\Models\ProjectLoadFile::class)
                <a
                    href="{{ route('project-load-files.create') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-add"></i> @lang('crud.common.create')
                </a>
                @endcan
            </div>
        </div>
    </div>
</div>
@endsection