routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProjectUserController;
use App\Http\Controllers\ProjectDataController;
use App\Http\Controllers\ProjectMetaController;
use App\Http\Controllers\ProjectLoadFileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/home/{uid}', [HomeController::class, 'setActiveProject']);
Route::get('/sessions', [HomeController::class, 'SessionsDate']);

Route::prefix('/')
    ->middleware('auth')
    ->group(function () {
        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);

        Route::resource('users', UserController::class);
        Route::resource('project-users', ProjectUserController::class);
        Route::resource('project-load-files', ProjectLoadFileController::class);
        Route::get('all-project-data', [
            ProjectDataController::class,
            'index',
        ])->name('all-project-data.index');
        Route::post('all-project-data', [
            ProjectDataController::class,
            'store',
        ])->name('all-project-data.store');
        Route::get('all-project-data/create', [
            ProjectDataController::class,
            'create',
        ])->name('all-project-data.create');
        Route::get('all-project-data/{projectData}', [
            ProjectDataController::class,
            'show',
        ])->name('all-project-data.show');
        Route::get('all-project-data/{projectData}/edit', [
            ProjectDataController::class,
            'edit',
        ])->name('all-project-data.edit');
        Route::put('all-project-data/{projectData}', [
            ProjectDataController::class,
            'update',
        ])->name('all-project-data.update');
        Route::delete('all-project-data/{projectData}', [
            ProjectDataController::class,
            'destroy',
        ])->name('all-project-data.destroy');

        Route::resource('projects', ProjectController::class);
        Route::resource('project-metas', ProjectMetaController::class);
    });

app/Models/ProjectMeta.php
<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class ProjectMeta extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'project_id',
        'name',
        'params',
        'chart_name',
        'on_main',
    ];

    protected $searchableFields = ['*'];

    protected $table = 'project_metas';

    protected $casts = [
        'on_main' => 'boolean',
    ];

    public function project()
    {
        return $this->belongsTo(Project::class);
    }
}

app/Http/Controllers/Api/ProjectMetaController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\ProjectMeta;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\ProjectMetaResource;
use App\Http\Resources\ProjectMetaCollection;
use App\Http\Requests\ProjectMetaStoreRequest;
use App\Http\Requests\ProjectMetaUpdateRequest;

class ProjectMetaController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', ProjectMeta::class);

        $search = $request->get('search', '');

        $projectMetas = ProjectMeta::search($search)
            ->latest()
            ->paginate();

        return new ProjectMetaCollection($projectMetas);
    }

    /**
     * @param \App\Http\Requests\ProjectMetaStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectMetaStoreRequest $request)
    {
        $this->authorize('create', ProjectMeta::class);

        $validated = $request->validated();

        $projectMeta = ProjectMeta::create($validated);

        return new ProjectMetaResource($projectMeta);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectMeta $projectMeta
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, ProjectMeta $projectMeta)
    {
        $this->authorize('view', $projectMeta);

        return new ProjectMetaResource($projectMeta);
    }

    /**
     * @param \App\Http\Requests\ProjectMetaUpdateRequest $request
     * @param \App\Models\ProjectMeta $projectMeta
     * @return \Illuminate\Http\Response
     */
    public function update(
        ProjectMetaUpdateRequest $request,
        ProjectMeta $projectMeta
    ) {
        $this->authorize('update', $projectMeta);

        $validated = $request->validated();

        $projectMeta->update($validated);

        return new ProjectMetaResource($projectMeta);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectMeta $projectMeta
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, ProjectMeta $projectMeta)
    {
        $this->authorize('delete', $projectMeta);

        $projectMeta->delete();

        return response()->noContent();
    }
}

app/Http/Controllers/ProjectMetaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use App\Models\ProjectMeta;
use Illuminate\Http\Request;
use App\Http\Requests\ProjectMetaStoreRequest;
use App\Http\Requests\ProjectMetaUpdateRequest;

class ProjectMetaController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', ProjectMeta::class);

        $search = $request->get('search', '');

        $projectMetas = ProjectMeta::search($search)
            ->latest()
            ->paginate(5)
            ->withQueryString();

        return view(
            'app.project_metas.index',
            compact('projectMetas', 'search')
        );
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $this->authorize('create', ProjectMeta::class);

        $projects = Project::pluck('name', 'id');

        return view('app.project_metas.create', compact('projects'));
    }

    /**
     * @param \App\Http\Requests\ProjectMetaStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectMetaStoreRequest $request)
    {
        $this->authorize('create', ProjectMeta::class);

        $validated = $request->validated();

        $projectMeta = ProjectMeta::create($validated);

        return redirect()
            ->route('project-metas.edit', $projectMeta)
            ->withSuccess(__('crud.common.created'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectMeta $projectMeta
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, ProjectMeta $projectMeta)
    {
        $this->authorize('view', $projectMeta);

        return view('app.project_metas.show', compact('projectMeta'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectMeta $projectMeta
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, ProjectMeta $projectMeta)
    {
        $this->authorize('update', $projectMeta);

        $projects = Project::pluck('name', 'id');

        return view(
            'app.project_metas.edit',
            compact('projectMeta', 'projects')
        );
    }

    /**
     * @param \App\Http\Requests\ProjectMetaUpdateRequest $request
     * @param \App\Models\ProjectMeta $projectMeta
     * @return \Illuminate\Http\Response
     */
    public function update(
        ProjectMetaUpdateRequest $request,
        ProjectMeta $projectMeta
    ) {
        $this->authorize('update', $projectMeta);

        $validated = $request->validated();

        $projectMeta->update($validated);

        return redirect()
            ->route('project-metas.edit', $projectMeta)
            ->withSuccess(__('crud.common.saved'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectMeta $projectMeta
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, ProjectMeta $projectMeta)
    {
        $this->authorize('delete', $projectMeta);

        $projectMeta->delete();

        return redirect()
            ->route('project-metas.index')
            ->withSuccess(__('crud.common.removed'));
    }
}

resources/views/app/project_metas/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('project-metas.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.project_metas.create_title')
            </h4>

            <x-form
                method="POST"
                action="{{ route('project-metas.store') }}"
                class="mt-4"
            >
                @include('app.project_metas.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('project-metas.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.create')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

resources/views/app/project_metas/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('project-metas.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.project_metas.edit_title')
            </h4>

            <x-form
                method="PUT"
                action="{{ route('project-metas.update', $projectMeta) }}"
                class="mt-4"
            >
                @include('app.project_metas.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('project-metas.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <a
                        href="{{ route('project-metas.create') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-add text-primary"></i>
                        @lang('crud.common.create')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.update')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

resources/views/app/project_metas/form-inputs.blade.php
@php $editing = isset($projectMeta) @endphp

<div class="row">
    <x-inputs.group class="col-sm-12">
        <x-inputs.select name="project_id" label="Project" required>
            @php $selected = old('project_id', ($editing ? $projectMeta->project_id : '')) @endphp
            <option disabled {{ empty($selected) ? 'selected' : '' }}>Please select the Project</option>
            @foreach($projects as $value => $label)
            <option value="{{ $value }}" {{ $selected == $value ? 'selected' : '' }} >{{ $label }}</option>
            @endforeach
        </x-inputs.select>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12">
        <x-inputs.text
            name="name"
            label="Name"
            value="{{ old('name', ($editing ? $projectMeta->name : '')) }}"
            maxlength="255"
            placeholder="Name"
            required
        ></x-inputs.text>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12">
        <x-inputs.textarea name="params" label="Params" maxlength="255" required
            >{{ old('params', ($editing ? $projectMeta->params : ''))
            }}</x-inputs.textarea
        >
    </x-inputs.group>

    <x-inputs.group class="col-sm-12">
        <x-inputs.text
            name="chart_name"
            label="Chart Name"
            value="{{ old('chart_name', ($editing ? $projectMeta->chart_name : '')) }}"
            maxlength="255"
            placeholder="Chart Name"
            required
        ></x-inputs.text>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12">
        <x-inputs.checkbox
            name="on_main"
            label="On Main"
            :checked="old('on_main', ($editing ? $projectMeta->on_main : 0))"
        ></x-inputs.checkbox>
    </x-inputs.group>
</div>

resources/views/app/project_metas/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="searchbar mt-0 mb-4">
        <div class="row">
            <div class="col-md-6">
                <form>
                    <div class="input-group">
                        <input
                            id="indexSearch"
                            type="text"
                            name="search"
                            placeholder="{{ __('crud.common.search') }}"
                            value="{{ $search ?? '' }}"
                            class="form-control"
                            autocomplete="off"
                        />
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon ion-md-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-6 text-right">
                @can('create', App\Models\ProjectMeta::class)
                <a
                    href="{{ route('project-metas.create') }}"
                    class="btn btn-primary"
                >
                    <i class="icon ion-md-add"></i> @lang('crud.common.create')
                </a>
                @endcan
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div style="display: flex; justify-content: space-between;">
                <h4 class="card-title">
                    @lang('crud.project_metas.index_title')
                </h4>
            </div>

            <div class="table-responsive">
                <table class="table table-borderless table-hover">
                    <thead>
                        <tr>
                            <th class="text-left">
                                @lang('crud.project_metas.inputs.project_id')
                            </th>
                            <th class="text-left">
                                @lang('crud.project_metas.inputs.name')
                            </th>
                            <th class="text-left">
                                @lang('crud.project_metas.inputs.params')
                            </th>
                            <th class="text-left">
                                @lang('crud.project_metas.inputs.chart_name')
                            </th>
                            <th class="text-left">
                                @lang('crud.project_metas.inputs.on_main')
                            </th>
                            <th class="text-center">
                                @lang('crud.common.actions')
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($projectMetas as $projectMeta)
                        <tr>
                            <td>
                                {{ optional($projectMeta->project)->name ?? '-'
                                }}
                            </td>
                            <td>{{ $projectMeta->name ?? '-' }}</td>
                            <td>{{ $projectMeta->params ?? '-' }}</td>
                            <td>{{ $projectMeta->chart_name ?? '-' }}</td>
                            <td>{{ $projectMeta->on_main ?? '-' }}</td>
                            <td class="text-center" style="width: 134px;">
                                <div
                                    role="group"
                                    aria-label="Row Actions"
                                    class="btn-group"
                                >
                                    @can('update', $projectMeta)
                                    <a
                                        href="{{ route('project-metas.edit', $projectMeta) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-create"></i>
                                        </button>
                                    </a>
                                    @endcan @can('view', $projectMeta)
                                    <a
                                        href="{{ route('project-metas.show', $projectMeta) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-eye"></i>
                                        </button>
                                    </a>
                                    @endcan @can('delete', $projectMeta)
                                    <form
                                        action="{{ route('project-metas.destroy', $projectMeta) }}"
                                        method="POST"
                                        onsubmit="return confirm('{{ __('crud.common.are_you_sure') }}')"
                                    >
                                        @csrf @method('DELETE')
                                        <button
                                            type="submit"
                                            class="btn btn-light text-danger"
                                        >
                                            <i class="icon ion-md-trash"></i>
                                        </button>
                                    </form>
                                    @endcan
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="6">
                                @lang('crud.common.no_items_found')
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="6">{!! $projectMetas->render() !!}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/project_metas/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('project-metas.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.project_metas.show_title')
            </h4>

            <div class="mt-4">
                <div class="mb-4">
                    <h5>@lang('crud.project_metas.inputs.project_id')</h5>
                    <span
                        >{{ optional($projectMeta->project)->name ?? '-'
                        }}</span
                    >
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.project_metas.inputs.name')</h5>
                    <span>{{ $projectMeta->name ?? '-' }}</span>
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.project_metas.inputs.params')</h5>
                    <span>{{ $projectMeta->params ?? '-' }}</span>
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.project_metas.inputs.chart_name')</h5>
                    <span>{{ $projectMeta->chart_name ?? '-' }}</span>
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.project_metas.inputs.on_main')</h5>
                    <span>{{ $projectMeta->on_main ?? '-' }}</span>
                </div>
            </div>

            <div class="mt-4">
                <a
                    href="{{ route('project-metas.index') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-return-left"></i>
                    @lang('crud.common.back')
                </a>

                @can('create', App\Models\ProjectMeta::class)
                <a
                    href="{{ route('project-metas.create') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-add"></i> @lang('crud.common.create')
                </a>
                @endcan
            </div>
        </div>
    </div>
</div>
@endsection