routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProjectUserController;
use App\Http\Controllers\ProjectDataController;
use App\Http\Controllers\ProjectMetaController;
use App\Http\Controllers\ProjectLoadFileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/home/{uid}', [HomeController::class, 'setActiveProject']);
Route::get('/sessions', [HomeController::class, 'SessionsDate']);

Route::prefix('/')
    ->middleware('auth')
    ->group(function () {
        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);

        Route::resource('users', UserController::class);
        Route::resource('project-users', ProjectUserController::class);
        Route::resource('project-load-files', ProjectLoadFileController::class);
        Route::get('all-project-data', [
            ProjectDataController::class,
            'index',
        ])->name('all-project-data.index');
        Route::post('all-project-data', [
            ProjectDataController::class,
            'store',
        ])->name('all-project-data.store');
        Route::get('all-project-data/create', [
            ProjectDataController::class,
            'create',
        ])->name('all-project-data.create');
        Route::get('all-project-data/{projectData}', [
            ProjectDataController::class,
            'show',
        ])->name('all-project-data.show');
        Route::get('all-project-data/{projectData}/edit', [
            ProjectDataController::class,
            'edit',
        ])->name('all-project-data.edit');
        Route::put('all-project-data/{projectData}', [
            ProjectDataController::class,
            'update',
        ])->name('all-project-data.update');
        Route::delete('all-project-data/{projectData}', [
            ProjectDataController::class,
            'destroy',
        ])->name('all-project-data.destroy');

        Route::resource('projects', ProjectController::class);
        Route::resource('project-metas', ProjectMetaController::class);
    });

app/Models/ProjectUser.php
<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class ProjectUser extends Model
{
    use HasFactory;
    use Searchable;
    use SoftDeletes;

    protected $fillable = ['user_id', 'project_id'];

    protected $searchableFields = ['*'];

    protected $table = 'project_users';

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function project()
    {
        return $this->belongsTo(Project::class);
    }
}

app/Http/Controllers/Api/ProjectUserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\ProjectUser;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\ProjectUserResource;
use App\Http\Resources\ProjectUserCollection;
use App\Http\Requests\ProjectUserStoreRequest;
use App\Http\Requests\ProjectUserUpdateRequest;

class ProjectUserController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', ProjectUser::class);

        $search = $request->get('search', '');

        $projectUsers = ProjectUser::search($search)
            ->latest()
            ->paginate();

        return new ProjectUserCollection($projectUsers);
    }

    /**
     * @param \App\Http\Requests\ProjectUserStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectUserStoreRequest $request)
    {
        $this->authorize('create', ProjectUser::class);

        $validated = $request->validated();

        $projectUser = ProjectUser::create($validated);

        return new ProjectUserResource($projectUser);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectUser $projectUser
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, ProjectUser $projectUser)
    {
        $this->authorize('view', $projectUser);

        return new ProjectUserResource($projectUser);
    }

    /**
     * @param \App\Http\Requests\ProjectUserUpdateRequest $request
     * @param \App\Models\ProjectUser $projectUser
     * @return \Illuminate\Http\Response
     */
    public function update(
        ProjectUserUpdateRequest $request,
        ProjectUser $projectUser
    ) {
        $this->authorize('update', $projectUser);

        $validated = $request->validated();

        $projectUser->update($validated);

        return new ProjectUserResource($projectUser);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectUser $projectUser
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, ProjectUser $projectUser)
    {
        $this->authorize('delete', $projectUser);

        $projectUser->delete();

        return response()->noContent();
    }
}

app/Http/Controllers/ProjectUserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Project;
use App\Models\ProjectUser;
use Illuminate\Http\Request;
use App\Http\Requests\ProjectUserStoreRequest;
use App\Http\Requests\ProjectUserUpdateRequest;

class ProjectUserController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', ProjectUser::class);

        $search = $request->get('search', '');

        $projectUsers = ProjectUser::search($search)
            ->latest()
            ->paginate(5)
            ->withQueryString();

        return view(
            'app.project_users.index',
            compact('projectUsers', 'search')
        );
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $this->authorize('create', ProjectUser::class);

        $users = User::pluck('name', 'id');
        $projects = Project::pluck('name', 'id');

        return view('app.project_users.create', compact('users', 'projects'));
    }

    /**
     * @param \App\Http\Requests\ProjectUserStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectUserStoreRequest $request)
    {
        $this->authorize('create', ProjectUser::class);

        $validated = $request->validated();

        $projectUser = ProjectUser::create($validated);

        return redirect()
            ->route('project-users.edit', $projectUser)
            ->withSuccess(__('crud.common.created'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectUser $projectUser
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, ProjectUser $projectUser)
    {
        $this->authorize('view', $projectUser);

        return view('app.project_users.show', compact('projectUser'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectUser $projectUser
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, ProjectUser $projectUser)
    {
        $this->authorize('update', $projectUser);

        $users = User::pluck('name', 'id');
        $projects = Project::pluck('name', 'id');

        return view(
            'app.project_users.edit',
            compact('projectUser', 'users', 'projects')
        );
    }

    /**
     * @param \App\Http\Requests\ProjectUserUpdateRequest $request
     * @param \App\Models\ProjectUser $projectUser
     * @return \Illuminate\Http\Response
     */
    public function update(
        ProjectUserUpdateRequest $request,
        ProjectUser $projectUser
    ) {
        $this->authorize('update', $projectUser);

        $validated = $request->validated();

        $projectUser->update($validated);

        return redirect()
            ->route('project-users.edit', $projectUser)
            ->withSuccess(__('crud.common.saved'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\ProjectUser $projectUser
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, ProjectUser $projectUser)
    {
        $this->authorize('delete', $projectUser);

        $projectUser->delete();

        return redirect()
            ->route('project-users.index')
            ->withSuccess(__('crud.common.removed'));
    }
}

resources/views/app/project_users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('project-users.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.project_users.create_title')
            </h4>

            <x-form
                method="POST"
                action="{{ route('project-users.store') }}"
                class="mt-4"
            >
                @include('app.project_users.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('project-users.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.create')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

resources/views/app/project_users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('project-users.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.project_users.edit_title')
            </h4>

            <x-form
                method="PUT"
                action="{{ route('project-users.update', $projectUser) }}"
                class="mt-4"
            >
                @include('app.project_users.form-inputs')

                <div class="mt-4">
                    <a
                        href="{{ route('project-users.index') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <a
                        href="{{ route('project-users.create') }}"
                        class="btn btn-light"
                    >
                        <i class="icon ion-md-add text-primary"></i>
                        @lang('crud.common.create')
                    </a>

                    <button type="submit" class="btn btn-primary float-right">
                        <i class="icon ion-md-save"></i>
                        @lang('crud.common.update')
                    </button>
                </div>
            </x-form>
        </div>
    </div>
</div>
@endsection

resources/views/app/project_users/form-inputs.blade.php
@php $editing = isset($projectUser) @endphp

<div class="row">
    <x-inputs.group class="col-sm-12">
        <x-inputs.select name="user_id" label="User" required>
            @php $selected = old('user_id', ($editing ? $projectUser->user_id : '')) @endphp
            <option disabled {{ empty($selected) ? 'selected' : '' }}>Please select the User</option>
            @foreach($users as $value => $label)
            <option value="{{ $value }}" {{ $selected == $value ? 'selected' : '' }} >{{ $label }}</option>
            @endforeach
        </x-inputs.select>
    </x-inputs.group>

    <x-inputs.group class="col-sm-12">
        <x-inputs.select name="project_id" label="Project" required>
            @php $selected = old('project_id', ($editing ? $projectUser->project_id : '')) @endphp
            <option disabled {{ empty($selected) ? 'selected' : '' }}>Please select the Project</option>
            @foreach($projects as $value => $label)
            <option value="{{ $value }}" {{ $selected == $value ? 'selected' : '' }} >{{ $label }}</option>
            @endforeach
        </x-inputs.select>
    </x-inputs.group>
</div>

resources/views/app/project_users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="searchbar mt-0 mb-4">
        <div class="row">
            <div class="col-md-6">
                <form>
                    <div class="input-group">
                        <input
                            id="indexSearch"
                            type="text"
                            name="search"
                            placeholder="{{ __('crud.common.search') }}"
                            value="{{ $search ?? '' }}"
                            class="form-control"
                            autocomplete="off"
                        />
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon ion-md-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-6 text-right">
                @can('create', App\Models\ProjectUser::class)
                <a
                    href="{{ route('project-users.create') }}"
                    class="btn btn-primary"
                >
                    <i class="icon ion-md-add"></i> @lang('crud.common.create')
                </a>
                @endcan
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div style="display: flex; justify-content: space-between;">
                <h4 class="card-title">
                    @lang('crud.project_users.index_title')
                </h4>
            </div>

            <div class="table-responsive">
                <table class="table table-borderless table-hover">
                    <thead>
                        <tr>
                            <th class="text-left">
                                @lang('crud.project_users.inputs.user_id')
                            </th>
                            <th class="text-left">
                                @lang('crud.project_users.inputs.project_id')
                            </th>
                            <th class="text-center">
                                @lang('crud.common.actions')
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($projectUsers as $projectUser)
                        <tr>
                            <td>
                                {{ optional($projectUser->user)->name ?? '-' }}
                            </td>
                            <td>
                                {{ optional($projectUser->project)->name ?? '-'
                                }}
                            </td>
                            <td class="text-center" style="width: 134px;">
                                <div
                                    role="group"
                                    aria-label="Row Actions"
                                    class="btn-group"
                                >
                                    @can('update', $projectUser)
                                    <a
                                        href="{{ route('project-users.edit', $projectUser) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-create"></i>
                                        </button>
                                    </a>
                                    @endcan @can('view', $projectUser)
                                    <a
                                        href="{{ route('project-users.show', $projectUser) }}"
                                    >
                                        <button
                                            type="button"
                                            class="btn btn-light"
                                        >
                                            <i class="icon ion-md-eye"></i>
                                        </button>
                                    </a>
                                    @endcan @can('delete', $projectUser)
                                    <form
                                        action="{{ route('project-users.destroy', $projectUser) }}"
                                        method="POST"
                                        onsubmit="return confirm('{{ __('crud.common.are_you_sure') }}')"
                                    >
                                        @csrf @method('DELETE')
                                        <button
                                            type="submit"
                                            class="btn btn-light text-danger"
                                        >
                                            <i class="icon ion-md-trash"></i>
                                        </button>
                                    </form>
                                    @endcan
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="3">
                                @lang('crud.common.no_items_found')
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3">{!! $projectUsers->render() !!}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/project_users/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ route('project-users.index') }}" class="mr-4"
                    ><i class="icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.project_users.show_title')
            </h4>

            <div class="mt-4">
                <div class="mb-4">
                    <h5>@lang('crud.project_users.inputs.user_id')</h5>
                    <span>{{ optional($projectUser->user)->name ?? '-' }}</span>
                </div>
                <div class="mb-4">
                    <h5>@lang('crud.project_users.inputs.project_id')</h5>
                    <span
                        >{{ optional($projectUser->project)->name ?? '-'
                        }}</span
                    >
                </div>
            </div>

            <div class="mt-4">
                <a
                    href="{{ route('project-users.index') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-return-left"></i>
                    @lang('crud.common.back')
                </a>

                @can('create', App\Models\ProjectUser::class)
                <a
                    href="{{ route('project-users.create') }}"
                    class="btn btn-light"
                >
                    <i class="icon ion-md-add"></i> @lang('crud.common.create')
                </a>
                @endcan
            </div>
        </div>
    </div>
</div>
@endsection